services:
  app:
    container_name: berserkr_app
    build: .
    ports:
      - "51733:51733"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    tty: true
    stdin_open: true
    working_dir: /app
